name: Automate the update of stock list files

on:
  schedule:
    # Asia/Kuala_Lumpur around 6pm, weekdays only
    - cron: "0 10 * * 1,2,3,4,5"
    - cron: "17 * * * *"
jobs:
  build:
    name: Rebuild list files
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the source
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install and cache
        uses: bahmutov/npm-install@HEAD

      - name: Run script
        run: cd packages/data && npm run "update-data:skip-commit"

      - name: Commit changes
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: GitHub Actions Bot
          author_email: <>
          message: "Update stock list files"
          add: "stock-list.json stock-list-human.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
